#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# cleanCase removes time dirs/logs; alpha.map is an extra file this solver
# leaves behind that cleanCase itself doesn't remove.
cleanCase && rm -f 0/alpha.map

#------------------------------------------------------------------------------
