#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# cleanCase removes time directories/logs; alpha.map is an extra leftover
# file some runs of this solver create and isn't cleaned by cleanCase itself.
cleanCase && rm -f 0/alpha.map

#------------------------------------------------------------------------------
